<template>
  <div>
    <h3>重点人员</h3>
    <el-row>
      <button>人员A</button>
      <button>人员B</button>
      <button>人员C</button>
      <button>人员D</button>
    </el-row>
    <h3>小区内人员</h3>
    <el-row>
      <button>重点挑头</button>
      <button>积极参与</button>
      <button>关注人员</button>
      <button>一般人员</button>
    </el-row>
    <h3>重点事件</h3>
    <el-row>
      <button>重点事件1</button>
      <button>重点事件2</button>
      <button>重点事件3</button>
      <button>重点事件4</button>
    </el-row>
    <h3>重点群体</h3>
    <el-row>
      <button>群体1</button>
      <button>群体2</button>
      <button>群体3</button>
    </el-row>
  </div>
</template>

<script>
export default {};
</script>
